[tool.poetry]
name = "computorv1"
version = "0.1.0"
description = ""
authors = ["ctelma"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.1"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
